server:
  port: 8080

spring:
  servlet:
    # 파일 업로드
    multipart: 
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  output:
    ansi:
      # 터미널에 컬러 출력
      enabled: ALWAYS
  web:
    resources:
      cache:
        cachecontrol:
          # 정적 리소스에 대한 캐시 사용 안함
          no-cache: true
  ai:
    openai:
      # API 키
      api-key: ${OPENAI_API_KEY}

logging:
  pattern:
    console: '%clr(%-5level){green} %clr(%logger.%M\(\)){cyan}: %msg%n'